### ISSUE TITLE
Error in avscan wrapper ?

### ISSUE THREAD

**Issue by jcajkovic** [malice-plugins/avast#1]
Hi I've troubles with the wrapper written in go.

I've testing the script and it was failing whenever I send testing virus file. Container failed completely when I was in web mode.

The issue I found is that when you run the scan command (output, err := utils.RunCommand(ctx, "scan", "-abfu", path)) it will return exit status 0 code when no infected files was found, otherwise it return exit status 1. I'm afraid that your assert function just kill the script afterwards.

Can you please check that ?

btw from documentation of avast:

EXIT STATUS
       The exit status is 0 if no infected files are found and 1
       otherwise. If an error occurred, the exit  status  is  2.
       Infected  status takes precedence over error status, thus
              a scan where some file could  not  be  scanned  and  some
       infection was found returns 1.

https://files.avast.com/files/documentation/techdoc-avast-linux-en.pdf

the fix should be easy and even you do not need to check the string output of the scan command and rely purely on that

**Comment by blacktop** [comment]
Thank you for bringing this to my attention!  

I found similar issues in other AVs.  I used to ignore errors from running commands, but thought that wasn't a good idea as in Go all errors should be handled as a golang convention.

You can see how I fixed sophos and fprot here: https://github.com/malice-plugins/fprot/blob/master/scan.go#L60

It feels like a weird way to handle it, not very clean.

I think it should still check for errors because there might be other ways that the RunCommand could fail?

I am still trying to figure out the cleanest/simplest way of doing plugins in this way.

I will fix it for **avast** soon.  I moved all the **official** malice plugins into this new org and am going through them one by one adding better tests etc etc

**Comment by blacktop** [comment]
So I saw it was returning exit code 2 which is a valid error.

The reason it was code 2 was because the license expired.

I have made many updates including a check for an expired license before a scan is attempted.

Thank you again for letting me know and please let me know if there is still issues and...

Thanks for using **malice** 😁

**Comment by jcajkovic** [comment]
thanks for fix it should work, I'm going to test that.
